[package]
name = "muc"
version = "0.2.0"
edition = "2024"

[workspace]
members = [".", "crates/mu_wasm"]

[dependencies]
serde_json = "1.0.145"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
ureq = { version = "3.1.2", default-features = true }
